import { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useDemoController } from '../../stores/demoController';

// Document types from our data structure
interface Document {
  id: string;
  type: 'RPA' | 'Disclosure';
  propertyId: string;
  title: string;
  status: 'pending-signature' | 'signed';
  createdBy: string;
  createdAt: string;
  pdf: string;
}

// Mock RPA data for the demo
const demoRPA: Document = {
  id: 'doc-rpa-8615',
  type: 'RPA',
  propertyId: 'prop-8615',
  title: 'Residential Purchase Agreement',
  status: 'pending-signature',
  createdBy: 'user-agent-1',
  createdAt: '2024-06-01T10:00:00Z',
  pdf: '/assets/documents/rpa-8615.pdf'
};

// Form fields that will be auto-filled
interface RPAFields {
  propertyAddress: string;
  purchasePrice: string;
  buyerName: string;
  sellerName: string;
  agentName: string;
  escrowCompany: string;
  closingDate: string;
  earnestMoney: string;
  loanAmount: string;
  downPayment: string;
}

// Mock form data for auto-fill animation
const demoRPAData: RPAFields = {
  propertyAddress: '8615 Circle R Course Ln, Escondido, CA 92026',
  purchasePrice: '$1,250,000',
  buyerName: 'John Smith',
  sellerName: 'Jane Doe',
  agentName: 'Sarah Johnson',
  escrowCompany: 'First American Title',
  closingDate: 'July 15, 2024',
  earnestMoney: '$25,000',
  loanAmount: '$1,000,000',
  downPayment: '$250,000'
};

export const DemoDocumentGeneration = () => {
  const { trackAction, demoSpeed } = useDemoController();
  const [isGenerating, setIsGenerating] = useState(true);
  const [isComplete, setIsComplete] = useState(false);
  const [currentField, setCurrentField] = useState<keyof RPAFields | null>(null);

  // Auto-advance demo based on speed
  useEffect(() => {
    const timers: number[] = [];
    const baseTiming = {
      normal: 1200,  // 1.2 seconds for document generation
      fast: 600,     // 0.6 seconds for fast mode
      instant: 100   // 0.1 seconds for instant mode
    }[demoSpeed];

    // Simulate document generation with field-by-field auto-fill
    const fields: (keyof RPAFields)[] = [
      'propertyAddress',
      'purchasePrice',
      'buyerName',
      'sellerName',
      'agentName',
      'escrowCompany',
      'closingDate',
      'earnestMoney',
      'loanAmount',
      'downPayment'
    ];

    // Start generation
    timers.push(
      window.setTimeout(() => {
        setIsGenerating(true);
        trackAction('rpa_generation_started');
      }, 0)
    );

    // Auto-fill fields with animation
    fields.forEach((field, index) => {
      timers.push(
        window.setTimeout(() => {
          setCurrentField(field);
        }, (index * baseTiming) / fields.length)
      );
    });

    // Complete generation
    timers.push(
      window.setTimeout(() => {
        setIsGenerating(false);
        setIsComplete(true);
        trackAction('rpa_generated');
      }, baseTiming)
    );

    return () => timers.forEach(clearTimeout);
  }, [demoSpeed, trackAction]);

  return (
    <div className="max-w-4xl mx-auto">
      <div className="bg-white rounded-lg shadow-lg overflow-hidden">
        {/* Document Header */}
        <div className="p-6 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{demoRPA.title}</h1>
              <p className="text-gray-600">Generated for {demoRPAData.propertyAddress}</p>
            </div>
            <div className="text-right">
              <div className="text-sm text-gray-500">Generated by</div>
              <div className="font-medium text-gray-900">Sarah Johnson</div>
            </div>
          </div>
        </div>

        {/* Document Preview */}
        <div className="relative min-h-[600px] bg-gray-50 p-6">
          {/* PDF Preview Container */}
          <div className="relative bg-white shadow-lg rounded-lg overflow-hidden">
            {/* PDF Preview (using a mock for now) */}
            <div className="p-8 space-y-6">
              {/* Document Header */}
              <div className="text-center border-b pb-4">
                <h2 className="text-xl font-bold text-gray-900">Residential Purchase Agreement</h2>
                <p className="text-gray-600">California Association of Realtors</p>
              </div>

              {/* Form Fields with Auto-fill Animation */}
              <div className="space-y-4">
                {Object.entries(demoRPAData).map(([key, value]) => (
                  <motion.div
                    key={key}
                    className={`p-3 rounded ${
                      currentField === key
                        ? 'bg-blue-50 border border-blue-200'
                        : 'bg-gray-50 border border-gray-200'
                    }`}
                    initial={currentField === key ? { scale: 0.95 } : false}
                    animate={currentField === key ? { scale: 1 } : false}
                    transition={{ duration: 0.2 }}
                  >
                    <div className="text-sm text-gray-500 capitalize">
                      {key.replace(/([A-Z])/g, ' $1').trim()}
                    </div>
                    <div className="font-medium text-gray-900">{value}</div>
                  </motion.div>
                ))}
              </div>
            </div>

            {/* Generation Overlay */}
            <AnimatePresence>
              {isGenerating && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  className="absolute inset-0 bg-white/80 backdrop-blur-sm flex items-center justify-center"
                >
                  <div className="text-center">
                    <div className="w-16 h-16 border-4 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                    <div className="text-lg font-medium text-gray-900">Generating RPA...</div>
                    <div className="text-sm text-gray-500 mt-2">
                      {currentField
                        ? `Filling ${currentField.replace(/([A-Z])/g, ' $1').toLowerCase()}...`
                        : 'Preparing document...'}
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Completion Overlay */}
            <AnimatePresence>
              {isComplete && (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -20 }}
                  className="absolute bottom-4 right-4 bg-green-50 border border-green-200 rounded-lg p-4 shadow-lg"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center">
                      <svg className="w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                    </div>
                    <div>
                      <div className="font-medium text-green-900">RPA Generated</div>
                      <div className="text-sm text-green-600">Ready for signatures</div>
                    </div>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="p-6 border-t border-gray-200 bg-gray-50">
          <div className="flex gap-4">
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="flex-1 py-3 px-6 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition-colors"
              onClick={() => trackAction('signature_sent')}
            >
              Send for Signatures
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              className="py-3 px-6 bg-white text-gray-700 rounded-lg font-semibold border border-gray-300 hover:bg-gray-50 transition-colors"
            >
              Download PDF
            </motion.button>
          </div>
        </div>
      </div>
    </div>
  );
}; 